package interfaces;



import conexao.Conexao;
import dao.AlugarDAO;
import dao.CategoriaDAO;
import dao.ClienteDAO;
import dao.EnderecoDAO;
import dao.LoginDAO;
import dao.VeiculoDAO;
import static interfaces.home.con;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;



public class alugar extends javax.swing.JFrame {
    public static Connection con;
    public String GRG;
    public String GPLACA;
    

    /**
     * Creates new form alugar
     */
    public alugar(Connection con) {
        this.con = con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PROXIMO = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        FINALISAR = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelHORA = new javax.swing.JLabel();

        setTitle("Locação de Veículo");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar Cliente");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Nome");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("RG");

        jLabel2.setText("Filtros da pesquisa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PROXIMO.setText("Próximo Passo");
        PROXIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROXIMOActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Excluir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setText("Atividades Acadêmicas  © Michael ja©kon 2016. All Rights Reserved");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PROXIMO))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(447, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton4)))
                    .addGap(9, 9, 9)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROXIMO)
                    .addComponent(jButton2)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton4)
                        .addComponent(jButton1))
                    .addGap(304, 304, 304)))
        );

        jTabbedPane1.addTab("Selecione o Cliente", jPanel2);

        jLabel3.setText("Pesquisar Veículo");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Placa");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ano");

        jLabel4.setText("Filtros da Pesquisa");

        jLabel5.setText("Listar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Disponíveis" }));

        jScrollPane2.setWheelScrollingEnabled(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Cor", "Ano", "Placa", "Nº Portas", "Categoria", "Disponível"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        FINALISAR.setText("Finalizar Locação");
        FINALISAR.setEnabled(false);
        FINALISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINALISARActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel6.setText("Quilometragem do Veiculo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86)
                                .addComponent(jLabelHORA))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FINALISAR)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jLabelHORA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FINALISAR)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Selecione o Veículo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
      public void clearTable(){
   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
   DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    model.getDataVector().removeAllElements();
    model2.getDataVector().removeAllElements();
    revalidate();
}
      
      
    
     public void atualizarTabela(){
          try{
              clearTable();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             ClienteDAO clie = new ClienteDAO(con); 
             ResultSet rs = clie.retrive();
            while(rs.next()){
                String nome = rs.getString("nome");
                String telefone = rs.getString("telefone");
                long rg = rs.getLong("rg");
              
                System.out.println(rg);
                model.addRow(new Object[]{nome,rg,telefone});
            } 
            
            DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
             VeiculoDAO v = new VeiculoDAO(con); 
             LoginDAO lg = new LoginDAO(con);
             CategoriaDAO cDAO = new CategoriaDAO(con);
             
             rs = v.retrive();
            while(rs.next()){
                String placa = rs.getString("placa");
                int fk_unidade = rs.getInt("fk_unidade");        
                String unidade = lg.retriveNome(fk_unidade);   
                String fk_categoria = rs.getString("fk_categoria");
                String cor = rs.getString("cor");
                int numportas = rs.getInt("numportas");
                int ano = rs.getInt("ano");
                String disponivel = rs.getString("disponivel");
                String modelo = rs.getString("modelo");
              
                model2.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
            }    
       }catch(SQLException e){
            System.out.println("errooooo");
        }
    }
     
                                 

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualizarTabela();
          Timer timer = new Timer(1000, new hora());
        timer.start();  
       
     
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       atualizarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        FINALISAR.setEnabled(true);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void FINALISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINALISARActionPerformed
        try{
            int linha =  jTable2.getSelectedRow();
            GPLACA = (jTable2.getValueAt(linha, 3)).toString();
            VeiculoDAO v = new VeiculoDAO(con);

            if(v.disponivel(GPLACA)){

                int KM = Integer.parseInt(jTextField3.getText());

                AlugarDAO alu = new AlugarDAO(con);
                alu.create(GRG, GPLACA, KM);
                JOptionPane.showMessageDialog(this,"Locação realizada com sucesso!");
                this.setVisible(false);

            }else {
                JOptionPane.showMessageDialog(this, "O veículo não está disponível para locação.");
            }

        }catch(SQLException e){
            System.out.println("Erro de sqllll");
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"Erro1: Selecione o cliente a ser editado.");
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Erro2: Digite quilometragem do veiculo.");
        }

    }//GEN-LAST:event_FINALISARActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearTable();

        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        try{

            VeiculoDAO clie = new VeiculoDAO(con);
            LoginDAO lg = new LoginDAO(con);
            if (jComboBox1.getSelectedItem().equals("Todos")){
                if (jRadioButton1.isSelected()){
                    ResultSet rs = clie.retrivePlaca(jTextField2.getText());
                    while(rs.next()){
                        String placa = rs.getString("placa");
                        int fk_unidade = rs.getInt("fk_unidade");
                        String unidade = lg.retriveNome(fk_unidade);
                        String fk_categoria = rs.getString("fk_categoria");
                        String cor = rs.getString("cor");
                        int numportas = rs.getInt("numportas");
                        int ano = rs.getInt("ano");
                        String disponivel = rs.getString("disponivel");
                        String modelo = rs.getString("modelo");

                        model2.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
                    }
                }else if(jRadioButton2.isSelected()){
                    ResultSet rs = clie.retriveAno(jTextField2.getText());
                    while(rs.next()){
                        String placa = rs.getString("placa");
                        int fk_unidade = rs.getInt("fk_unidade");
                        String unidade = lg.retriveNome(fk_unidade);
                        String fk_categoria = rs.getString("fk_categoria");
                        String cor = rs.getString("cor");
                        int numportas = rs.getInt("numportas");
                        int ano = rs.getInt("ano");
                        String disponivel = rs.getString("disponivel");
                        String modelo = rs.getString("modelo");

                        model2.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
                    }}
                    else{
                        JOptionPane.showMessageDialog(this, "Selecione o filtro da pesquisa");

                    }}else if(jComboBox1.getSelectedItem().equals("Disponíveis")){
                        if (jRadioButton1.isSelected()){
                            ResultSet rs = clie.retrivePlacaD(jTextField2.getText());
                            while(rs.next()){
                                String placa = rs.getString("placa");
                                int fk_unidade = rs.getInt("fk_unidade");
                                String unidade = lg.retriveNome(fk_unidade);
                                String fk_categoria = rs.getString("fk_categoria");
                                String cor = rs.getString("cor");
                                int numportas = rs.getInt("numportas");
                                int ano = rs.getInt("ano");
                                String disponivel = rs.getString("disponivel");
                                String modelo = rs.getString("modelo");

                                model2.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
                            }
                        }else if(jRadioButton2.isSelected()){
                            ResultSet rs = clie.retriveAnoD(jTextField2.getText());
                            while(rs.next()){
                                String placa = rs.getString("placa");
                                int fk_unidade = rs.getInt("fk_unidade");
                                String unidade = lg.retriveNome(fk_unidade);
                                String fk_categoria = rs.getString("fk_categoria");
                                String cor = rs.getString("cor");
                                int numportas = rs.getInt("numportas");
                                int ano = rs.getInt("ano");
                                String disponivel = rs.getString("disponivel");
                                String modelo = rs.getString("modelo");

                                model2.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
                            }}else{
                                JOptionPane.showMessageDialog(this, "Selecione o filtro da pesquisa");
                            }

                        }

                    }catch(SQLException e){
                        System.out.println("errooooo");
                    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            int linha =  jTable1.getSelectedRow();
            String RG = (jTable1.getValueAt(linha, 1)).toString();
            AlugarDAO alu = new AlugarDAO(con);
            if(alu.retriveExistente(RG)){
                JOptionPane.showMessageDialog(this,"Erro: não é possivel excuir. Locação ativa!");
            }else{
                ClienteDAO clie = new ClienteDAO(con);
                EnderecoDAO end = new EnderecoDAO(con);
                int fk_endereco = clie.delete(RG);
                end.delete(fk_endereco);

                jTable1.repaint();
                atualizarTabela();
            }
        }catch(SQLException e){
            System.out.println("errooooo");
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"Erro: Selecione o cliente a ser excluido.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            int linha =  jTable1.getSelectedRow();
            if (linha!=-1){
                String RG = (jTable1.getValueAt(linha, 1)).toString();
                new editarCliente(RG,con).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,"Erro: Selecione o cliente a ser editado.");
            }}catch(java.lang.ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(this,"Erro1: Selecione o cliente a ser editado.");
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new cadastrarCliente(con).setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void PROXIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROXIMOActionPerformed
        int linha =  jTable1.getSelectedRow();
        if (linha != -1){

            try{
                GRG = (jTable1.getValueAt(linha, 1)).toString();
                System.out.println("meu amigo"+ GRG);
                AlugarDAO alu = new AlugarDAO(con);
                System.out.println(alu.retriveExistente(GRG));
                if (alu.retriveExistente(GRG)){
                    JOptionPane.showMessageDialog(this,"Erro: Já existe uma locação ativa para este cliente.");
                }else{
                    jTabbedPane1.setSelectedIndex(1);
                }
            }catch(SQLException e){
                System.out.println("Erro de SQL");
            }catch(java.lang.ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(this,"Erro1: Selecione o cliente");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Erro: Selecione um cliente.");
        }

    }//GEN-LAST:event_PROXIMOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearTable();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try{

            ClienteDAO clie = new ClienteDAO(con);
            if (jRadioButton3.isSelected()){
                ResultSet rs = clie.retriveNome(jTextField1.getText());
                while(rs.next()){
                    String nome = rs.getString("nome");
                    String telefone = rs.getString("telefone");
                    long rg = rs.getLong("rg");

                    System.out.println(rg);
                    model.addRow(new Object[]{nome,rg,telefone});
                }
            }else if(jRadioButton4.isSelected()){
                ResultSet rs = clie.retriverg(jTextField1.getText());
                while(rs.next()){
                    String nome = rs.getString("nome");
                    String telefone = rs.getString("telefone");
                    long rg = rs.getLong("rg");
                    System.out.println(rg);
                    model.addRow(new Object[]{nome,rg,telefone});
                }
            }else {
                JOptionPane.showMessageDialog(this, "Selecione um dos filtros");
            }
        }catch(SQLException e){
            System.out.println("errooooo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alugar(con).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FINALISAR;
    private javax.swing.JButton PROXIMO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHORA;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener{
    @Override
        public void actionPerformed (ActionEvent e ){
    Calendar now = Calendar.getInstance();
    jLabelHORA.setText(String.format("%1$tH:%1$tM:%1$tS  ", now));
     }

    
    }

}

