package interfaces;


import conexao.Conexao;
import dao.CategoriaDAO;
import dao.ClienteDAO;
import dao.LoginDAO;
import dao.VeiculoDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class listarVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form listarClientes
     */
    public static Connection con;
    public static int unidade;
    public listarVeiculos(Connection con, int unidade) {
        this.con = con;
        this.unidade = unidade;
        initComponents();
    }

    public void preencheTabela(){
     
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setTitle("Veículos");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Pesquisar Veículo");

        jLabel2.setText("Filtros da pesquisa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Cor", "Ano", "Placa", "Nº Portas", "Categoria", "Disponível", "Unidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Placa");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Ano");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Disponíveis" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Listar");

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar Veículo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel29.setText("Atividades Acadêmicas  © Michael ja©kon 2016. All Rights Reserved");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton4))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jComboBox1, 0, 1, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    
     public void clearTable(){
   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.getDataVector().removeAllElements();
    revalidate();
}
    
    
    
     public void atualizarTabela(){
          try{
              clearTable();
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             VeiculoDAO v = new VeiculoDAO(con); 
             LoginDAO lg = new LoginDAO(con);
             CategoriaDAO cDAO = new CategoriaDAO(con);
             
             ResultSet rs = v.retrive();
            while(rs.next()){
                String placa = rs.getString("placa");
                int fk_unidade = rs.getInt("fk_unidade");        
                String unidade = lg.retriveNome(fk_unidade);   
                String fk_categoria = rs.getString("fk_categoria");
                String cor = rs.getString("cor");
                int numportas = rs.getInt("numportas");
                int ano = rs.getInt("ano");
                String disponivel = rs.getString("disponivel");
                String modelo = rs.getString("modelo");
              
                model.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
            }               
       }catch(SQLException e){
            System.out.println("erro sql");
        }
    }
    
  
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     atualizarTabela();   
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //exclui a porra toda
        
       try{
       int linha =  jTable1.getSelectedRow();
       String placa = (jTable1.getValueAt(linha, 3)).toString();   
       VeiculoDAO v = new VeiculoDAO(con);
       if (v.disponivel(placa)){
       
       
       int excluiu = v.delete(placa);
          
       if(excluiu == 1){
         JOptionPane.showMessageDialog(this, "Veículo excluído com sucesso.");
       }else {
         JOptionPane.showMessageDialog(this, "ERRO: Exclusão não efetuada.");
       }}else{
         JOptionPane.showMessageDialog(this, "ERRO: Exclusão não efetuada, o veiculo encontra-se locado!"); 
       }
     
     
       }catch(SQLException e){
            System.out.println("erro de sql");
       }catch(java.lang.ArrayIndexOutOfBoundsException e){
           JOptionPane.showMessageDialog(this, "Selecione um veículo.");
       }
       
       jTable1.repaint();
       atualizarTabela();
       
     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new cadastrarVeiculo(con,unidade).setVisible(true);    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
       clearTable();
   
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try{
            
        VeiculoDAO clie = new VeiculoDAO(con);
        LoginDAO lg = new LoginDAO(con);
        if (jComboBox1.getSelectedItem().equals("Todos")){
        if (jRadioButton3.isSelected()){
            ResultSet rs = clie.retrivePlaca(jTextField1.getText());
            while(rs.next()){
                String placa = rs.getString("placa");
                int fk_unidade = rs.getInt("fk_unidade");        
                String unidade = lg.retriveNome(fk_unidade);   
                String fk_categoria = rs.getString("fk_categoria");
                String cor = rs.getString("cor");
                int numportas = rs.getInt("numportas");
                int ano = rs.getInt("ano");
                String disponivel = rs.getString("disponivel");
                String modelo = rs.getString("modelo");
              
                model.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
            }            
        }else if(jRadioButton4.isSelected()){
            ResultSet rs = clie.retriveAno(jTextField1.getText());
            while(rs.next()){
                String placa = rs.getString("placa");
                int fk_unidade = rs.getInt("fk_unidade");        
                String unidade = lg.retriveNome(fk_unidade);   
                String fk_categoria = rs.getString("fk_categoria");
                String cor = rs.getString("cor");
                int numportas = rs.getInt("numportas");
                int ano = rs.getInt("ano");
                String disponivel = rs.getString("disponivel");
                String modelo = rs.getString("modelo");
              
                model.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
            }}
        else{
            JOptionPane.showMessageDialog(this, "Selecione o filtro da pesquisa");
            
        }}else if(jComboBox1.getSelectedItem().equals("Disponíveis")){
            if (jRadioButton3.isSelected()){
            ResultSet rs = clie.retrivePlacaD(jTextField1.getText());
            while(rs.next()){
                String placa = rs.getString("placa");
                int fk_unidade = rs.getInt("fk_unidade");        
                String unidade = lg.retriveNome(fk_unidade);   
                String fk_categoria = rs.getString("fk_categoria");
                String cor = rs.getString("cor");
                int numportas = rs.getInt("numportas");
                int ano = rs.getInt("ano");
                String disponivel = rs.getString("disponivel");
                String modelo = rs.getString("modelo");
              
                model.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
            }            
        }else if(jRadioButton4.isSelected()){
            ResultSet rs = clie.retriveAnoD(jTextField1.getText());
            while(rs.next()){
                String placa = rs.getString("placa");
                int fk_unidade = rs.getInt("fk_unidade");        
                String unidade = lg.retriveNome(fk_unidade);   
                String fk_categoria = rs.getString("fk_categoria");
                String cor = rs.getString("cor");
                int numportas = rs.getInt("numportas");
                int ano = rs.getInt("ano");
                String disponivel = rs.getString("disponivel");
                String modelo = rs.getString("modelo");
              
                model.addRow(new Object[]{modelo, cor, ano, placa, numportas, fk_categoria, disponivel, unidade});
            }}else{
            JOptionPane.showMessageDialog(this, "Selecione o filtro da pesquisa");
        }
            
            
            
        }
        
        }catch(SQLException e){
            System.out.println("errooooo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        atualizarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
